// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEnUtImJWGlHkwr8AXIOiaWVNapsbnvzY',
    appId: '1:770188279623:android:1688360a5a571772401662',
    messagingSenderId: '770188279623',
    projectId: 'notes-faa68',
    storageBucket: 'notes-faa68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybHZQLPL0QiCZz8yn59bLm-xwSeEO8FY',
    appId: '1:770188279623:ios:8de5f44883bdd957401662',
    messagingSenderId: '770188279623',
    projectId: 'notes-faa68',
    storageBucket: 'notes-faa68.appspot.com',
    iosClientId: '770188279623-77fcfijdasfaa7g7c17b6jm1no8uqrgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
